desktop_branch PR
sibomana123/MV__Portfolio pull request #4
Opened 2023-07-17 13:08 UTC by sibomana123

For this project, I  used the knowledge gained in the previous week and I apply and used Flexbox CSS grid and media queries to make a responsive portfolio, this project seems good in all devices that have these sizes 375px, 640px, 768px, and above

2023-07-17 15:42 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @sibomana123 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![TN6](https://user-images.githubusercontent.com/57408419/242633152-ef9bf425-5bec-4c19-bada-7713cd7e55f2.gif)


## To highlight :champagne: 

- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 


## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-17 15:42 UTC, joel-kalema commented on desktopView.css
> +  }
- [ ] Good job working on the desktop version 🥇 , however, you need need to fix some parts, Kindly make sure to stick to the design as much as possible, I could be better if you fix your margins, font-size, and padding, let's take an example from this line of code:
````css
.description {
      .
      .
    height: 845px;
  }

  .header {
       .
    padding: 200px 150px 2px 200px;
    font-size: 48px;
       .
  }

  .parg {
       .
       .
    padding: 15px 100px 2px 200px;
    width: 90%;
       .
  }

  .let__go {
    padding: 1.2rem 100px 0 200px;
       .
  }

  .social__media {
       .
    padding: 12px 100px 0 200px;
  }
````

2023-07-17 15:42 UTC, joel-kalema commented on desktopView.css
> +    display: flex;
- [ ] Kindly, make user you stack to the design (margins, colors, font-size,... ) as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=You%20must%20replicate%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20info%20from%20the%20Figma%20templates.) 😃. 

#### Figma design
![Screenshot 2023-07-17 164849](https://github.com/sibomana123/MV__Portfolio/assets/57408419/a38c70cd-1fb0-4476-bf53-10232ba11ebb)

#### Your design
![Screenshot 2023-07-17 165148](https://github.com/sibomana123/MV__Portfolio/assets/57408419/d159c7b0-46a3-4e5a-ad6e-46bc7500866e)

2023-07-17 15:42 UTC, joel-kalema commented on index.html
> +    <h1>Contact Me</h1>
- [ ] Also there, make sure to stick to the design 💪. Kindly, fix it 👍   

> | | Figma template | | Your project | |
> |-|---------|-|--------|-|
> | |![Screenshot 2023-07-17 172446](https://github.com/sibomana123/MV__Portfolio/assets/57408419/8489beba-e5a5-45dd-81d8-c3ed31778c17)| |![Screenshot 2023-07-17 173830](https://github.com/sibomana123/MV__Portfolio/assets/57408419/d305fd49-1bfc-4b32-8413-6a8f1c37a63f)| |

2023-07-19 14:38 UTC, sibomana123 commented
After Review @joel-kalema  I tried to solve what he told me to change and used  font size style and color related to template

2023-07-19 15:22 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @sibomana123, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  Desktop Version worked on :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

- [OPTIONAL] While trying to style your desktop version of your portfolio, you must ensure that it does not affect your mobile version. At this moment, your mobile version is greatly affected. Kindly look into that and fix.

### Mobile Version
[mobile.webm](https://github.com/sibomana123/MV__Portfolio/assets/26597432/58f75a8e-1bd6-4086-a245-2581642167c6)



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 15:22 UTC, Qoosim commented on desktopVersion.css
> +  }
- [ ] Great job implementing required changes from the previous reviewer. However, there're few things to take care before you move on.
- [ ] Kindly ensure that you produce a close replica of the figma design at every section. I noticed that the width and the height of the project image is too much and as a result it affects how the project info should align beside the image. Kindly check the two screenshots and walk your design alongside the figma design. Pay attention to those areas I marked with red.

### Your Design
![your-project-card](https://github.com/sibomana123/MV__Portfolio/assets/26597432/770ec798-b54c-4b3e-94bf-e75807e060ea)

### Figma Design
![temp-project=card](https://github.com/sibomana123/MV__Portfolio/assets/26597432/230fce07-0bcc-48cf-b713-81850643569c)

2023-07-19 15:22 UTC, Qoosim commented on desktopVersion.css
> +  }
- [OPTIONAL] Kindly make the text inside your button in a single line as it is on the figma design.

### Your Design
![your-about](https://github.com/sibomana123/MV__Portfolio/assets/26597432/89bb373d-d012-409c-8304-b7b394d2d4f8)

### Figma Design 
![temp-about](https://github.com/sibomana123/MV__Portfolio/assets/26597432/cfbe872a-7704-4350-8bc4-7411aef4ccc5)

2023-07-19 15:22 UTC, Qoosim commented on desktopVersion.css
> +}
- [ ] As mentioned by the previous reviewer, you're required to stick to the figma design as close as possible. Your contact me section is quite different from the figma design. Kindly compare the two screenshots below and walk your design alongside the figma design

### Your Design
![your-form](https://github.com/sibomana123/MV__Portfolio/assets/26597432/a2f80841-6ef2-4055-afd8-9fd0037e4961)

### Figam Design
![temp-form](https://github.com/sibomana123/MV__Portfolio/assets/26597432/64d8cc7b-3093-4179-acdb-fd3497437a0b)

2023-07-19 20:15 UTC, Alusp requested changes
Hi @sibomana123, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [ ] Linters set-up ✔️
- [ ] Commit messages descriptive ✔️
- [ ] Professional GitHub Flow used ✔️
- [ ] Profesional PR Summary ✔️



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] While trying to style your desktop version of your portfolio, you must ensure that it does not affect your mobile version. At this moment, your mobile version is greatly affected. Kindly look into that and fix it.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 20:15 UTC, Alusp commented on desktopVersion.css
> +  }
- [ ] Great job in implementing the changes requested by the previous reviewers, however, as mentioned by the previous reviewer, Kindly ensure that you produce a close replica of the Figma design in every section. I noticed that the width and the height of the project image are too much and as a result it affects how the project info should align beside the image.  matching your design to the given design requirements enhances the chances of creating a successful and well-rounded design solution that meets the needs of users, complies with regulations, and performs effectively and efficiently. :slightly_smiling_face: 

The example below shows the difference between yours and the accepted one: :arrow_down: 

 <table>
    <tr>
      <td>Yours </td>
      <td>Figma</td>
    </tr>
    <tr>
      <td>

 
![Student de](https://github.com/sibomana123/MV__Portfolio/assets/43528594/e5804660-7ec1-44b4-b36c-e51a8013bc6f)

 
</td>
      <td>

![Figma De](https://github.com/sibomana123/MV__Portfolio/assets/43528594/7af24d1a-b5e1-48ad-9443-f04d5ad105b2)

</td>
    </tr>
  </table>

2023-07-20 13:01 UTC, merged